apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: muzixapp
  name: muzixapp
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    run: muzixapp
  type: NodePort
status:
  loadBalancer: {}
